version: '3'

services:
  app:
    container_name: app
    build: .
    command: yarn dev
    depends_on:
      - mongo
    ports:
      - '3333:8080'
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: mongo
    image: mongo:4
    restart: always
    logging:
      driver: 'none' ## Para desativar os logs
    ports:
      - 12345:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
